---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
  - 2.7.0
before_install: gem install bundler -v 2.2.28
script: bundle exec rspec --format documentation --order random
branches:
  only:
    - master
    - develop
